version: '3'
networks:
  app-tier:
    driver: bridge

services:
  db:
    image: bitnami/mongodb:latest
    env_file:
      - .env
    networks:
      - app-tier
    ports:
      - "27017:27017"

 # un-comment to create a server in localhost:8081
 # this can be used to see mongo database manually
 # mongo-express:
 #   image: mongo-express
 #   networks:
 #     - app-tier
 #   environment:
 #     - ME_CONFIG_MONGODB_ADMINUSERNAME=root
 #     - ME_CONFIG_MONGODB_ADMINPASSWORD=development
 #     - ME_CONFIG_MONGODB_SERVER=db
 #   ports:
 #     - "8081:8081"


  web_app:
    build:
      dockerfile: Dockerfile
      context: .
    image: fastapi_boilerplate
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - app-tier
